version: '3'
services:
  stats:
    image: pytorch_ubuntu_env:v2.2
    user: jovyan
    ports:
      - "8080:8080"
    volumes:
      - ../:/home/jovyan/workdir
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]